<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */

?>
<?php $_product = $block->getProduct(); ?>
<div class="product actions product-item-actions">
<?php if ($_product->getProductStatus() == 1):?>
        <div class="product-status available"><span class="only-view"><?php /* @escapeNotVerified */ echo __('Nur abholung möglich -') ?></span><p><?php /* @escapeNotVerified */ echo __('Sle konnen den Artikel direkt in einer unserer Filialen abholen. Das Produkt 1st noch in ausreichender Menge vorhanden') ?></p></div>
<?php elseif($_product->getReserveAndCollect()): ?>
    
        <div class="product-status available"><span class="already-reserved"><?php /* @escapeNotVerified */ echo __('Nur abholung möglich -') ?></span><p><?php /* @escapeNotVerified */ echo __('Sie können den Artikel direkt in einer unserer Filialen reservieren und bequem abholen.') ?></p></div>
<?php elseif ($_product->isSaleable()):?>
        <div class="product-status available"><div class="stock available status-in-stock"><span><?php /* @escapeNotVerified */ echo __('Auf Lager') ?></span></div>
        <?php if($_product->getDeliveryTimeInDays()): ?>
            <div class="stock-count"><?php echo " - " .$_product->getDeliveryTimeInDays();?><span> <?php /* @escapeNotVerified */ echo  __('&nbsp Tage Lieferzeit') ?></span></div>
        <?php endif;?>
        </div>
<?php endif;?>
</div>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
         <?php if ($_product->getProductStatus() == 1):?>
                <?php $buttonTitle = __('Ansichtsprodukt'); ?>
                <div class="actions">
                    <button type="button"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary viewonly"
                            id="product-viewonly-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
        <?php else:?>
            
            <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                <div class="control">
                    <select class="input-text qty" name="qty" id="qty">
                        <?php 
                            $qty = 0;
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
                            $totalqty =  $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());
                            if($totalqty < 20)
                            {
                                $qty = 12;
                            }
                            else
                            {
                                $qty = 20;
                            }
                        ?>
                        <option selected="selected" value="1">1</option>
                        <?php for ($i=2; $i <= $qty; $i++):?>
                            <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                        <?php endfor; ?>
                    </select>
                </div> 
            </div>
            <?php endif; ?> 

            <?php if(!$_product->getReserveAndCollect()): ?>
                <?php $buttonTitle = __('Update Cart'); ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            <?php else: ?>
                <?php $buttonTitle = __('Jetzt reservieren'); ?>
                <div class="actions">
                    <input type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary reserve-collect"
                            id="product-reserveandcollect-button"
                            value="<?php /* @escapeNotVerified */ echo $buttonTitle ?>">
                    </input>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>
<?php else:?>
<div class="box-tocart">
    <div class="fieldset">
        <?php $buttonTitle = __('Ansichtsprodukt'); ?>
        <div class="actions">
            <button type="button"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary viewonly"
                    id="product-viewonly-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>

<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "validation": {},
            "addToCart": {
                "cartButtonId": "#product-updatecart-button",
                "cartForm": "#product_addtocart_form"
            }
        }
    }
</script>
<?php endif; ?>

<?php if ($_product->getReserveAndCollect()): ?>
<script>
require([
    "jquery"
], function($){
    $(document).ready(function(){         
        var actionUrl = "<?php echo $block->getBaseUrl() . 'storelocator/'; ?>";
        $("#product_reserve_form").attr("action", actionUrl);
        $(document).on("click", "#product-reserveandcollect-button", function(){
            // $("#product_addtocart_form").submit();
            $( "#product_reserve_form" ).submit();
        });
        
    });
});
</script>
<?php endif; ?>

