<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
//echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName());
?>
<?php if ($messages = $block->getMessages()): ?>
    <?php foreach ($messages as $message): ?>
        <h1><?php echo $block->escapeHtml($message) ?></h1>
    <?php endforeach; ?>
<?php endif; ?>

    <div class="block-title order">
        <strong>Artikel zurückschicken</strong>
        </div>

            <div class="retun-content">
                <p> <strong>Willkommen im Retourencenter!</strong><br>
                Um deine Artikel zurückzusenden und deine Rückerstattung zu erhalten, kannst du hier die Rücksendedokumente generieren. Bitte gib uns zuerst folgende Informationen: </p>
            </div>

<form class="form"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="returnrequest_orderid"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="orderno"><span><?php /* @escapeNotVerified */ echo __('Bestellnummer') ?></span></label>
            <div class="control">

                <input name="orderno" id="orderno" title="<?php /* @escapeNotVerified */ echo __('Bestellnummer') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>        
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="orderidform" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('WEITER') ?></span>
            </button>
        </div>
    </div>
</form>
