<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
//'Krish_Listajax/js/product/list/continue-btn'
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?php /* @escapeNotVerified */ echo __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">

        <?php foreach ($block->getAvailableOrders() as $_key => $_order):

            if($_key == 'position') continue;

            if($_key == 'price') { ?>
                <option class="<?php echo $_key.'_low'; ?>"

                        value="<?php echo 'price&product_list_dir=asc' ?>"
                        value="<?php echo $_key.'&product_list_dir=asc' ?>"

                    <?php if ($block->getCurrentDirection() == 'asc' && $block->isOrderCurrent($_key)): ?>
                        selected="selected"
                    <?php endif; ?>
                >
                    <?php echo $block->escapeHtml(__('PRICE: LOW TO HIGH')) ?>
                </option>
                <option class="<?php echo $_key.'_high'; ?>" value="<?php echo 'price&product_list_dir=desc' ?>"
                    <?php if ($block->getCurrentDirection() == 'desc' && $block->isOrderCurrent($_key)): ?>
                        selected="selected"
                    <?php endif; ?>
                ><?php echo $block->escapeHtml(__('PRICE: HIGH TO LOW')) ?>
                </option>
                <?php
            }
            else{
                ?>
                <option class="<?php echo $_key; ?>" value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                    <?php if ($block->isOrderCurrent($_key)): ?>
                        selected="selected"
                    <?php endif; ?>
                >
                    <?php echo $block->escapeHtml(__($_order)) ?>
                </option>
            <?php } ?>
        <?php endforeach; ?>
    </select>
    <?php /*if ($block->getCurrentDirection() == 'desc'): */?><!--
        <a title="<?php /*/* @escapeNotVerified */ //echo __('Set Ascending Direction') */?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?php /*/* @escapeNotVerified */ //echo __('Set Ascending Direction') */?></span>
        </a>
    <?php /*else: */?>
        <a title="<?php /*/* @escapeNotVerified */ //echo __('Set Descending Direction') */?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?php /*/* @escapeNotVerified */ //echo __('Set Descending Direction') */?></span>
        </a>
    --><?php /*endif; */?>
</div>