<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?php /* @escapeNotVerified */ echo __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <option value="<?php /* @escapeNotVerified */ echo 'short_by'; ?>"
            <?php if ($block->isOrderCurrent('short_by')): ?>
                selected="selected"
            <?php endif; ?>
            >
            <?php echo $block->escapeHtml(__("Sortierung")) ?>
        </option>
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                <?php if($_key == "name"):?>
                    <option value="<?php echo 'name&product_list_dir=asc'; ?>"<?php if($this->isOrderCurrent('name') && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>
                        <?php echo $block->escapeHtml(__("Al­pha­be­tisch A-Z")) ?>
                    </option>

                    <option value="<?php echo 'name&product_list_dir=desc'; ?>"<?php if($this->isOrderCurrent('name') && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>
                    <?php echo $block->escapeHtml(__("Alphabetisch Z-A")) ?>
                    </option>

                    <?php elseif($_key == "price"):?>
                            <option value="<?php /* @escapeNotVerified */ echo $_key.'&product_list_dir=asc'; ?>"<?php if($this->isOrderCurrent('price') && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>
                            <?php echo $block->escapeHtml(__("Preis - höchster zuerst")) ?>
                            </option>

                            <option value="<?php /* @escapeNotVerified */ echo $_key.'&product_list_dir=desc'; ?>"<?php if($this->isOrderCurrent('price') && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>
                            <?php echo $block->escapeHtml(__("Preis - niedrigster zuerst")) ?>
                            </option>
                    <?php elseif($_key == "position"):?>
                    <?php elseif($_key == "short_by"):?>
                    <?php else:?>
                        <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                            <?php if ($block->isOrderCurrent($_key)): ?>
                                selected="selected"
                            <?php endif; ?>
                            >
                            <?php echo $block->escapeHtml(__($_order)) ?>
                        </option>
                    <?php endif; ?>
        <?php endforeach; ?>
    </select>
    <!-- <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?> -->
</div>
