<?php $image = 'category_page_grid' ?>
<?php $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW ?>
<?php //$showWishlist = $slider->getDisplayWishlist()   ?>
<?php //$showCompare = $slider->getDisplayCompare()   ?>
<?php //$showCart = $slider->getDisplayCart()   ?>
<?php $showWishlist = true; ?>
<?php $showCompare = true; ?>
<?php $showCart = true; ?>
<?php $counter = 0; $listofcate = $this->loadcate();
$activeCate = count($listofcate);
?>
<?php if($activeCate > 0) : ?>
<div id="product-slider-wrapper">
    <div class="block block-product-slider slider-list bestsellers_manual">
        <div class="block-title title">
            <strong id="block-bestsellers_manual-heading" role="heading"
                    aria-level="2"><span><?php echo __('Dekorationen für den winter') ?></span></strong>
        </div>
        <?php
        $counter = 1;

        foreach ($listofcate as $category): ?>
            <?php
            $listofcatepro = $this->productCollections($category->getData('entity_id'));

            ?>
            <?php if(count($listofcatepro) > 0): ?>
            <div class="block-content content">
                <div class="products wrapper grid products-grid products-">
                    <ol class="products list items product-slider">

                        <?php foreach ($listofcatepro as $products): ?>
                            <?php $_productNameStripped = $block->stripTags($products->getName(), null, true); ?>
                            <?php $_item = $products; ?>
                            <?php $iterator = 1; ?>
                            <?php $counter++; ?>
                            <?php /* @escapeNotVerified */
                            echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <div class="product-item-info ">

                                <a href="<?php /* @escapeNotVerified */
                                echo $block->getProductUrl($products) ?>" class="product photo product-item-photo">
                                    <?php echo $block->getImage($products, $image)->toHtml(); ?>
                                    <div class="dis-tag"><?php echo $this->helper('ThinkIdeas\Additional\Helper\Data')->DisplayDiscountLabel($_item); ?></div>
                                </a>

                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name"><a class="product-item-link"
                                                                                      title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                                                                      href="<?php /* @escapeNotVerified */
                                                                                      echo $block->getProductUrl($_item) ?>">
                                            <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>
                                    <?php /* @escapeNotVerified */
                                    echo $block->getProductPrice($_item); ?>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available">
                                                                <span><?php /* @escapeNotVerified */
                                                                    echo __('Auf Lager') ?></span></div>
                                                            <?php if ($_item->getDeliveryTimeInDays()) { ?>
                                                                <div
                                                                    class="stock-count"><?php echo " -" . $_item->getDeliveryTimeInDays(); ?>
                                                                    <span> <?php /* @escapeNotVerified */
                                                                        echo __('Tage Lieferzeit') ?></span></div>
                                                            <?php } ?>
                                                        <?php endif; ?>

                                                        <div class="main-btn"><a class="action tocart primary"
                                                                                 href="<?php /* @escapeNotVerified */
                                                                                 echo $_item->getProductUrl() ?>"
                                                                                 title="<?php echo $_productNameStripped; ?>"><span><?php /* @escapeNotVerified */
                                                                    echo __('Zum Produkt') ?></span></a></div>
                                                        <?php /*if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                         <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ /*echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ /*echo __('Add to Cart') ?>">
                                                             <span><?php /* @escapeNotVerified */ /*echo __('Add to Cart') ?></span>
                                                         </button>
                                                     <?php else: ?>
                                                         <?php
                                                         $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                         $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                         ?>
                                                         <button class="action tocart primary"
                                                                 data-post='<?php /* @escapeNotVerified */ /*echo $postData; ?>'
                                                                 type="button" title="<?php /* @escapeNotVerified */ /*echo __('Add to Cart') ?>">
                                                             <span><?php /* @escapeNotVerified */ /*echo __('Add to Cart') ?></span>
                                                         </button>
                                                     <?php endif; */ ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <!--<div class="stock available"><span><?php /*/* @escapeNotVerified */ /*echo __('In stock') */ ?></span></div>-->
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <span><?php /* @escapeNotVerified */
                                                                    echo __('Nicht auf Lager') ?></span></div>
                                                            <?php if ($_item->getData('delivery_time_in_week')) { ?>
                                                                <div
                                                                    class="stock-count"><?php echo " -" . $_item->getData('delivery_time_in_week'); ?>
                                                                    <span> <?php /* @escapeNotVerified */
                                                                        echo __('Wochen Lieferzeit') ?></span></div>
                                                                <div class="main-btn"><a
                                                                        class="action tocart primary out-of-stock"
                                                                        href="<?php /* @escapeNotVerified */
                                                                        echo $_item->getProductUrl() ?>"
                                                                        title="<?php echo $_productNameStripped; ?>"><?php /* @escapeNotVerified */
                                                                        echo __('Leider Aktuell Ausverkauft') ?></a>
                                                                </div>
                                                            <?php } ?>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php /*if ($showWishlist || $showCompare): ?>
                                             <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                 <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                     <a href="#" data-post='<?php /* @escapeNotVerified */ /*echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ /*echo __('Add to Wish List') ?>">
                                                         <span><?php /* @escapeNotVerified */ /*echo __('Add to Wish List') ?></span>
                                                     </a>
                                                 <?php endif; ?>
                                                 <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                     <?php
                                                     $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                     ?>
                                                     <a href="#" class="action tocompare"
                                                        data-post='<?php /* @escapeNotVerified */ /*echo $compareHelper->getPostDataParams($_item); ?>'
                                                        data-role="add-to-links"
                                                        title="<?php /* @escapeNotVerified */ /*echo __('Add to Compare'); ?>">
                                                         <span><?php /* @escapeNotVerified */ /*echo __('Add to Compare') ?></span>
                                                     </a>
                                                 <?php endif; ?>
                                             </div>
                                         <?php endif; */ ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php echo ($iterator == count($_item) + 1) ? '</li>' : '' ?>
                        <?php endforeach; ?>
                    </ol>
                </div>
            </div>
            <div class="slider-count">
                <p><?php echo __((count($listofcatepro)) . " Produkte in dieser Kategorie"); ?></p>
                <a href="<?php echo $category->getData('url_path').'.html'; ?>"><?php echo __("ALLE PRODUKTE ANZEIGEN"); ?></a>
            </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
<script type="text/javascript">
    /*require(['jquery', 'slick'], function($){
     $(function(){
     $('.product-slider').slick({
     dots: false,
     infinite: true,
     slidesToShow: 4,
     slidesToScroll: 1,
     speed: 500,
     autoplay: false,
     autoplaySpeed: 1000,
     cssEase: 'linear',
     })
     })
     });*/


    require(['jquery', 'slick'], function ($) {
        $(function () {
            $('.product-slider').slick({
                dots: false,
                infinite: true,
                slidesToShow: 4,
                slidesToScroll: 1,
                speed: 500,
                autoplay: false,
                autoplaySpeed: 1000,
                cssEase: 'linear',
                rtl: false,
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    }
                ]
            })
        })
    });
</script>
<?php endif;  ?>
