
<?php $image = 'category_page_grid' ?>
<?php $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW ?>
<?php //$showWishlist = $slider->getDisplayWishlist()   ?>
<?php //$showCompare = $slider->getDisplayCompare()   ?>
<?php //$showCart = $slider->getDisplayCart()   ?>
<?php $showWishlist = true; ?>
<?php $showCompare = true; ?>
<?php $showCart = true; ?>
<?php $counter = 0; ?>
<?php $counter = 1; $listofcate = $this->loadcate(); $activeCate = count($listofcate); ?>
<?php
if($activeCate > 0) : ?>
    <div id="product-slider-wrapper">
        <div class="block block-product-slider slider-list bestsellers_manual" >
            <div class="block-title title">
                <strong id="block-bestsellers_manual-heading" role="heading" aria-level="2"><span><?php echo __('Empfehlungen von uns')?></span></strong>
            </div>
            <div id="loading" style="text-align: center; padding:40px 0 40px 0">
                <img src="<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                     alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                     >
            </div>
            <div class="block-content content" style="display: none">
                <div class="products wrapper grid products-grid products-">
                    <ol class="products list items product-slider">
                        <?php foreach ($listofcate as $category): ?>
                            <?php $listofcatepro = $this->productCollections($category->getData('entity_id')); ?>
                            <?php if(count($listofcatepro) > 0): ?>
                                <?php foreach ($listofcatepro as $products): ?>
                                    <?php $_productNameStripped = $block->stripTags($products->getName(), null, true); ?>
                                    <?php $_item = $products; ?>
                                    <?php 
                                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                        $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
                                        $totalqty =  $StockState->getStockQty($_item->getId(), $_item->getStore()->getWebsiteId());
                                    ?>
                                    <?php $iterator = 1; ?>
                                    <?php $counter++; ?>
                                    <?php
                                        $attribute_code = 'delivery_time';
                                        $deliveryWeek =  $_item->getResource()->getAttribute($attribute_code)->getFrontend()->getValue($_item);
                                        $attribute_code = 'delivery_time_color';
                                        $deliveryWeekColor =  $_item->getResource()->getAttribute($attribute_code)->getFrontend()->getValue($_item);
                                        $week = filter_var($deliveryWeek, FILTER_SANITIZE_NUMBER_INT);
                                    ?>
                                    <li class="item product product-item">
                                    <div class="product-item-info ">
                                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($products) ?>" class="product photo product-item-photo">
                                            <?php echo $block->getImage($products, $image)->toHtml(); ?>
                                        </a>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist" data-action="add-to-wishlist">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            </div>
                                        <?php endif; ?>
                                        <div class="product details product-item-details">
                                            <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                    <?php ;
                                                    if (strlen($_item->getName()) > 30)
                                                    {
                                                        $namestr = array();
                                                        $namestr[] = substr($_item->getName(), 0, 30);
                                                        $namestr[] = substr($_item->getName(), 30, strlen($_item->getName())-30);
                                                        $name = implode($namestr, "-");
                                                    }
                                                    else{
                                                        $name = $_item->getName();
                                                    }
                                                    ?>
                                                    <?php echo $block->escapeHtml($name) ?></a>
                                            </strong>
                                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                                <div class="product actions product-item-actions <?php echo strtolower($deliveryWeekColor); ?>">
                                                    <?php if ($showCart): ?>
                                                        <div class="actions-primary">
                                                            <?php //if ($_item->isSaleable() && $week != 6 && $week != 8): ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <?php if ($totalqty == 0  && $deliveryWeek == 'Sofort lieferbar'):?>
                                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Nicht auf Lager') ?></span></div>
                                                                        <?php if($_item->getData('delivery_time_in_week')): ?>
                                                                            <div class="stock-count"><?php echo " -" .$_item->getData('delivery_time_in_week');?><span> <?php /* @escapeNotVerified */ echo __('Wochen Lieferzeit') ?></span>
                                                                            </div>
                                                                        <?php endif;?>
                                                                <?php elseif (!$_item->getReserveAndCollect()): ?>
                                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('Auf Lager') ?></span></div>
                                                                    <?php if($_item->getDeliveryTimeInDays()){ ?>
                                                                        <div class="stock-count"><?php echo $_item->getDeliveryTimeInDays();?><span> <?php /* @escapeNotVerified */ echo __('Tage Lieferzeit') ?></span></div>
                                                                    <?php } ?>
                                                                <?php elseif ($_item->getProductStatus() == 1):?>
                                                                <div class="stock-count view-only-status"><span><?php /* @escapeNotVerified */ echo __('ANSICHTSPRODUKT') ?></span></div>
                                                                <?php else:?>
                                                                    <div class="stock available typerc-stock-status"><span><?php /* @escapeNotVerified */ echo __('Nur Abholung möglich ') ?></span></div>
                                                                <?php endif; ?>
                                                                
                                                                <?php if ($totalqty == 0  && $deliveryWeek == 'Sofort lieferbar'):?>
                                                                        <div class="main-btn"> <a class="action tocart primary out-of-stock" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php /* @escapeNotVerified */ echo __('Leider Aktuell Ausverkauft') ?></a>
                                                                        </div>
                                                                <?php elseif ($_item->getReserveAndCollect()):?>
                                                                    <div class="main-btn"><a class="action tocart primary reserved-btn" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><span><?php /* @escapeNotVerified */ echo __('In einer Filiale reservieren') ?></span></a></div>
                                                                <?php elseif ($_item->getProductStatus() == 1):?>
                                                                    <div class="main-btn"><a class="action tocart primary out-of-stock" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php /* @escapeNotVerified */ echo __('Ansichtsprodukt') ?></a></div>
                                                                <?php else:?>
                                                                    <div class="main-btn"><a class="action tocart primary" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><span><?php /* @escapeNotVerified */ echo __('Zum Produkt') ?></span></a></div>
                                                                <?php endif; ?>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Nicht auf Lager') ?></span></div>
                                                                <?php if($_item->getData('delivery_time_in_week')): ?>
                                                                    <div class="stock-count"><?php echo " -" .$_item->getData('delivery_time_in_week');?><span> <?php /* @escapeNotVerified */ echo __('Wochen Lieferzeit') ?></span>
                                                                    </div>
                                                                <?php endif;?>
                                                                <div class="main-btn"> <a class="action tocart primary out-of-stock" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php /* @escapeNotVerified */ echo __('Leider Aktuell Ausverkauft') ?></a>
                                                                </div>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php echo($iterator == count($_item)+1) ? '</li>' : '' ?>
                                <?php endforeach; ?>

                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ol>
                </div>
            </div>
        </div>
        <div class="slider-count" style="display: none;">
            <p><?php echo __((int)($counter - 1) . " Produkte in dieser Kategorie"); ?></p>
        </div>
    </div>
    <script type="text/javascript">
        require(['jquery', 'slickcat'], function($){
            $(function(){
                if(window.screen.width > 767){
                    $('.product-slider').slick({
                        dots: false,
                        infinite: true,
                        slidesToShow: 4,
                        slidesToScroll: 1,
                        speed: 500,
                        autoplay: false,
                        autoplaySpeed: 1000,
                        cssEase: 'linear',
                        rtl: false,
                        responsive: [
                            {
                                breakpoint: 1024,
                                settings: {
                                    slidesToShow: 3,
                                    slidesToScroll: 2                     }
                            },
                            {
                                breakpoint: 768,
                                settings: {
                                    slidesToShow: 2,
                                    slidesToScroll: 1                     }
                            },
                            {
                                breakpoint: 480,
                                settings: {
                                    slidesToShow: 1,
                                    slidesToScroll: 1                     }
                            }
                        ]
                    })
                    $(".block-product-slider .block-content").css("display","block");
                    $(".block-product-slider .slider-count").css("display","block");
                    $(".block-product-slider #loading").css("display","none");
                }
                else
                {
                    $('.block-slider').slick({
                        dots: true,
                        infinite: true,
                        slidesToShow: 1,
                        slidesToScroll: 1,
                        speed: 500,
                        autoplay: true,
                        autoplaySpeed: 2000,
                        cssEase: 'linear',
                        arrows:true,                         
                    })
                    $(".favorite-categories .block-slider").css("display","block");
                    $(".favorite-categories #loading").css("display","none");
                }


            })
        });

    </script>
<?php endif;  ?>