<?php /**
 * Copyright © 2016 thinkIdeas (http://www.thinkIdeas.co/) All rights reserved.
 */
?>
<?php $_items = $block->getSliderProductsCollection() ?>


<?php if(count($_items)==0) : ?>
    <?php return  ?>
<?php endif ?>

<?php $_helper = $this->helper('Magento\Catalog\Helper\Output') ?>
<?php $sliderId = $block->getSliderDisplayId() ?>
<?php $slider = $block->getSlider()  ?>

<?php $image = 'category_page_grid' ?>
<?php $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW ?>
<?php $viewMode = 'grid' ?>
<?php $class = $slider->getType() ?>
<?php $type = "" ?>
<?php $showWishlist = $slider->getDisplayWishlist() ?>
<?php $showCompare = $slider->getDisplayCompare() ?>
<?php $showCart = $slider->getDisplayCart() ?>

<div class="block block-product-slider slider-list <?php /* @escapeNotVerified */ echo $class; ?>" <?php echo $slider->getRtl() ? 'dir="rtl" ' : "" ?>  >
    <?php if($slider->getDisplayTitle()): ?>
        <div class="block-title title">
            <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><span><?php /* @escapeNotVerified */ echo $slider->getTitle() ?></span></strong>
        </div>
    <?php endif ?>
    <div id="loading" style="text-align: center; padding:40px 0 40px 0">
        <img src="<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
             alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
             >
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading" style="display:none">
        <?php if(!empty($_items)): ?>
            <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">

                <ol class="products list items product-slider<?php echo $sliderId ?>">
                    <?php foreach($_items as $collection): ?>
                        <?php $iterator = 1; ?>
                        <?php foreach ($collection as $_item):
                            $_productNameStripped = $block->stripTags($_item->getName(), null, true);
                            ?>
                            <?php 
                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
                                $totalqty =  $StockState->getStockQty($_item->getId(), $_item->getStore()->getWebsiteId());
                                $attribute_code = 'delivery_time';
                                $deliveryWeek =  $_item->getResource()->getAttribute($attribute_code)->getFrontend()->getValue($_item);
                                $attribute_code = 'delivery_time_color';
                                $deliveryWeekColor =  $_item->getResource()->getAttribute($attribute_code)->getFrontend()->getValue($_item);
                                $week = filter_var($deliveryWeek, FILTER_SANITIZE_NUMBER_INT);
                            ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <div class="product-item-info<?php echo $slider->getGrid() ? '' : '-'.$class ?> product-item-info">

                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                    <div class="dis-tag"><?php echo $this->helper('ThinkIdeas\Additional\Helper\Data')->DisplayDiscountLabel($_item); ?></div>
                                </a>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist" data-action="add-to-wishlist">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                        </a>
                                    </div>
                                <?php endif; ?>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                            <?php ;
                                            if (strlen($_item->getName()) > 30)
                                            {
                                                $namestr = array();
                                                $namestr[] = substr($_item->getName(), 0, 30);
                                                $namestr[] = substr($_item->getName(), 30, strlen($_item->getName())-30);
                                                $name = implode($namestr, "-");
                                            }
                                            else{
                                                $name = $_item->getName();
                                            }
                                            ?>
                                            <?php echo $block->escapeHtml($name) ?></a>
                                    </strong>


                                    <?php if($slider->getDisplayPrice()): ?>
                                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                                    <?php endif ?>
                                    <?php if ($templateType): ?>
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product actions product-item-actions <?php echo strtolower($deliveryWeekColor); ?>">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php //if ($_item->isSaleable() && $week != 6 && $week != 8): ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <?php if ($totalqty == 0  && $deliveryWeek == 'Sofort lieferbar'):?>
                                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Nicht auf Lager') ?></span></div>
                                                            <?php if($_item->getData('delivery_time_in_week')): ?>
                                                                <div class="stock-count"><?php echo " -" .$_item->getData('delivery_time_in_week');?><span> <?php /* @escapeNotVerified */ echo __('Wochen Lieferzeit') ?></span>
                                                                </div>
                                                            <?php endif;?>
                                                            <div class="main-btn"> <a class="action tocart primary out-of-stock" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php /* @escapeNotVerified */ echo __('Leider Aktuell Ausverkauft') ?></a>
                                                            </div>
                                                        <?php elseif (!$_item->getReserveAndCollect()): ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('Auf Lager') ?></span></div>
                                                            <?php if($_item->getDeliveryTimeInDays()){ ?>
                                                                <div class="stock-count"><?php echo $_item->getDeliveryTimeInDays();?><span> <?php /* @escapeNotVerified */ echo __('Tage Lieferzeit') ?></span></div>
                                                            <?php } ?>
                                                            <div class="main-btn"><a class="action tocart primary" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><span><?php /* @escapeNotVerified */ echo __('Zum Produkt') ?></span></a></div>
                                                        <?php elseif ($_item->getProductStatus() == 1):?>
                                                                <div class="stock-count view-only-status"><span><?php /* @escapeNotVerified */ echo __('ANSICHTSPRODUKT') ?></span></div>
                                                                <div class="main-btn"><a class="action tocart primary out-of-stock" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php /* @escapeNotVerified */ echo __('Ansichtsprodukt') ?></a></div>
                                                        <?php else:?>
                                                                <div class="stock available typerc-stock-status"><span><?php /* @escapeNotVerified */ echo __('Nur Abholung möglich ') ?></span></div>
                                                                <div class="main-btn"><a class="action tocart primary reserved-btn" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><span><?php /* @escapeNotVerified */ echo __('In einer Filiale reservieren') ?></span></a>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Nicht auf Lager') ?></span></div>
                                                        <?php if($_item->getData('delivery_time_in_week')): ?>
                                                            <div class="stock-count"><?php echo " -" .$_item->getData('delivery_time_in_week');?><span> <?php /* @escapeNotVerified */ echo __('Wochen Lieferzeit') ?></span>
                                                            </div>
                                                        <?php endif;?>
                                                        <div class="main-btn"> <a class="action tocart primary out-of-stock" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php /* @escapeNotVerified */ echo __('Leider Aktuell Ausverkauft') ?></a>
                                                        </div>

                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php echo($iterator == count($collection)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                        <?php

                        if ($class == "bestsellers_manual") {
                            break;;
                        } ?>
                    <?php endforeach ?>
                </ol>
            </div>
        <?php endif ?>
    </div>
    <div class="slider-count" style="display: none">
        <!-- <p><?php //echo __((int)($iterator - 1) . " Produkte in dieser Kategorie"); ?></p> -->
        <?php if ($class == "bestsellers_manual"):?>
            <a href="<?php  echo $block->getBaseUrlBestseller() . 'all-bestseller.html'; ?>"><?php echo __("ALLE ANZEIGEN"); ?></a>
        <?php else: ?>
            <p><?php echo __((int)($iterator - 1) . " Produkte in dieser Kategorie"); ?></p>
        <?php endif; ?>
    </div>
</div>
<?php if(!$slider->getGrid()): ?>
    <script>
        require(['jquery', 'slickproduct'], function($){
            $(function(){
                if(window.screen.width > 767){
                    $('.product-slider'+<?php echo $sliderId ?>).slick({
                        dots: <?php echo var_export((bool)$slider->getNavigation()) ?>,
                        infinite: <?php echo var_export((bool)$slider->getInfinite()) ?>,
                        slidesToShow: <?php echo $slider->getSlidesToShow() ?>,
                        slidesToScroll: <?php echo $slider->getSlidesToScroll() ?>,
                        speed: <?php echo $slider->getSpeed() ?>,
                        autoplay: <?php echo var_export((bool)$slider->getAutoplay()) ?>,
                        autoplaySpeed: <?php echo $slider->getAutoplaySpeed() ?>,
                        cssEase: 'linear',
                        rtl: <?php echo var_export((bool)$slider->getRtl()) ?>,
                        responsive: [
                            {
                                breakpoint: <?php echo $slider->getBreakpointLarge() ?>,
                                settings: {
                                    slidesToShow: <?php echo $slider->getLargeSlidesToShow() ?>,
                                    slidesToScroll: <?php echo $slider->getLargeSlidesToScroll() ?>
                                }
                            },
                            {
                                breakpoint: <?php echo $slider->getBreakpointMedium() ?>,
                                settings: {
                                    slidesToShow: <?php echo $slider->getMediumSlidesToShow() ?>,
                                    slidesToScroll: <?php echo $slider->getMediumSlidesToScroll() ?>
                                }
                            },
                            {
                                breakpoint: <?php echo $slider->getBreakpointSmall() ?>,
                                settings: {
                                    slidesToShow: <?php echo $slider->getSmallSlidesToShow() ?>,
                                    slidesToScroll: <?php echo $slider->getSmallSlidesToScroll() ?>
                                }
                            }
                        ]
                    })


                }

                $(".block-product-slider .block-content").css("display","block");
                $(".block-product-slider .slider-count").css("display","block");
                $(".block-product-slider #loading").css("display","none");
            })
        });
    </script>
<?php endif ?>

