<?php
/**
 * ThinkIdeas
 *
 * @category    ThinkIdeas
 * @package     ThinkIdeas_Faq
 *
 */
namespace ThinkIdeas\Faq\Block;
/**
 * Class Leftsidebar
 * @package ThinkIdeas\Faq\Block
 */
class Leftsidebar extends \ThinkIdeas\Faq\Block\Sidebar
{
    /**
     * @return $this
     */
    protected function _prepareLayout() {
        $isActive =  $this->_faqHelper->isEnableConfig();
        if ($this->_faqHelper->getSidebarPosition()=='sidebar-left'&& $isActive &&
            $this->_faqHelper->isShowSidebar()==1 ) {
            $this->setTemplate('sidebar.phtml');
        }
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}