<?php
/**
 * ThinkIdeas
 *
 * @category    ThinkIdeas
 * @package     ThinkIdeas_Faq
 *
 */
namespace ThinkIdeas\Faq\Block;
/**
 * Class Rightsidebar
 * @package ThinkIdeas\Faq\Block
 */
class Rightsidebar extends \ThinkIdeas\Faq\Block\Sidebar
{
    /**
     * @return $this
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    protected function _prepareLayout() {
        $isActive =  $this->_faqHelper->isEnableConfig();
        $allBlock = $this->getLayout()->getAllBlocks();
        $blockArray = array_keys($allBlock);
        if (in_array("faq.sidebar.left",$blockArray)) {
            if ($allBlock["faq.sidebar.left"]->getTemplate()) {
                return parent::_prepareLayout();
            }
        }
        if ($this->_faqHelper->getSidebarPosition()=='sidebar-right'&& $isActive &&
            $this->_faqHelper->isShowSidebar()==1 ) {
            $this->setTemplate('sidebar.phtml');
        }
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}