<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">

    <td data-th="<?php echo $block->escapeHtml(__('Item')); ?>" class="col item">
        <?php if ($block->hasProductUrl()):?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
           title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else:?>
            <span class="product-item-photo">
            <?php endif;?>
            <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
            <?php if ($block->hasProductUrl()):?>
        </a>
    <?php else: ?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()):?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?php echo $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()):?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>

            <!-- Start display addtional detail on cart page custom code -->


            <div>
                <div class="product-item-description"><?php echo $product->getShortDescription(); ?></div>
                <div class="product-item-sku"><label><?php echo __('Sku');?>: </label><?php echo $product->getSku(); ?></div>
                <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
                <div class="actions-primary">
                    <?php if ($product->isSaleable()): ?>
                        <?php if ($product->getIsSalable()): ?>
                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('Auf Lager') ?></span></div>
                            <?php if($product->getDeliveryTimeInDays()){ ?>
                                <div class="stock-count"><?php echo " -" .$product->getDeliveryTimeInDays();?><span> <?php /* @escapeNotVerified */ echo __('Tage Lieferzeit') ?></span></div>
                            <?php } ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if ($product->getIsSalable()): ?>
                            <!--<div class="stock available"><span><?php /*/* @escapeNotVerified */ //echo __('In stock') */?></span></div>-->
                        <?php else: ?>
                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Nicht auf Lager') ?></span></div>
                            <?php if($product->getData('delivery_time_in_week')){ ?>
                                <div class="stock-count"><?php echo " -" .$product->getDeliveryTimeInWeek();?><span> <?php /* @escapeNotVerified */ echo __('Wochen Lieferzeit') ?></span></div>
                            <?php } ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            </div>
            <!-- End custom code -->

        </div>
    </td>

    <?php /* ?>
        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?php /* @escapeNotVerified */ /*echo __('See price before order confirmation.'); ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ /*echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ /*echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ /*echo $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?php /* @escapeNotVerified */ /*echo __("What's this?"); ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <?php echo $block->getUnitPriceHtml($_item); ?>
            </td>
        <?php endif; ?>
        <?php */ ?>

    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <?php /* @escapeNotVerified */ echo $block->getQty() ?>
    </td>

    <!--<td class="col msrp" data-th="<?php /*echo $block->escapeHtml(__('Price')); */?>">
        <label><?php /*echo __('Sku');*/?>: </label><?php /*echo $product->getSku(); */?>
    </td>-->
    <!--        <div class="product-item-sku">-->
    <!--            <label>--><?php //echo __('Sku');?><!--:</label>-->
    <!--            --><?php //echo $product->getSku(); ?>
    <!--        </div>-->

    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?php echo $block->getRowTotalHtml($_item); ?>
        <?php endif; ?>
        <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
    </td>
</tr>
<?php /*
    <tr class="item-actions">
        <td colspan="100">
            <div class="actions-toolbar">
                <?php /* @escapeNotVerified */ /*echo $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
    <?php */?>
</tbody>
