<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */

?>
<?php $_product = $block->getProduct(); ?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$totalqty =  $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());
$attribute_code = 'delivery_time';
$deliveryWeek =  $_product->getResource()->getAttribute($attribute_code)->getFrontend()->getValue($_product);
$attribute_code = 'delivery_time_color';
$deliveryWeekColor =  $_product->getResource()->getAttribute($attribute_code)->getFrontend()->getValue($_product);
$week = filter_var($deliveryWeek, FILTER_SANITIZE_NUMBER_INT);
?>
<div class="price-incl-tax-label">
    <p class="tax-incl-label">
        <span>inkl. 19% MwSt. zzgl. Versand</span>
    </p>
</div>
<div class="product actions product-item-actions <?php echo strtolower($deliveryWeekColor); ?>">
<?php if ($_product->isSaleable()):?>
    <?php if ($_product->getProductStatus() == 1):?>
            <div class="product-status available"><span class="only-view"><?php /* @escapeNotVerified */ echo __('Nur abholung möglich -') ?></span><p><?php /* @escapeNotVerified */ echo __('Du kannst den Artikel direkt in einer unserer Filialen abholen. Das Produkt ist noch in ausreichender Menge vorhanden.') ?></p></div>
    <?php elseif($_product->getReserveAndCollect()): ?>
            <?php //echo"<pre/>"; print_r($week);exit; ?>
            <div class="product-status available"><span class="already-reserved"><?php /* @escapeNotVerified */ echo __('Nur Abholung möglich -') ?></span><p><?php /* @escapeNotVerified */ echo __('Du kannst den Artikel direkt in einer unserer Filialen abholen. Das Produkt ist noch in ausreichender Menge vorhanden.') ?></p></div>
    <?php elseif ($_product->getIsSalable() && $totalqty == 0  && $deliveryWeek == 'Sofort lieferbar'): ?>
        <div class="product-status unavailable"><span class="out-of-stock"></span></div>
    <?php else:?>
            <div class="product-status available"><div class="stock available status-in-stock"><span><?php /* @escapeNotVerified */ echo __('Auf Lager') ?></span></div>
            <?php if($_product->getDeliveryTimeInDays()): ?>
                <!-- <div class="stock-count"><?php //echo " - " .$_product->getDeliveryTimeInDays();?><span> 
                <?php /* @escapeNotVerified */ //echo  __('&nbsp Tage Lieferzeit') ?></span></div> -->
                <div class="stock-count"><?php echo $_product->getDeliveryTimeInDays();?><span> <?php /* @escapeNotVerified */ echo  __('&nbsp Tage Lieferzeit') ?></span></div>
            <?php endif;?>
            </div>
    <?php endif;?>
<?php else:?>
        <div class="product-status unavailable"><span class="out-of-stock"></span></div>
<?php endif; ?>
</div>

<?php //if ($_product->isSaleable() && $week != 6 && $week != 8): ?>
<?php if ($_product->getIsSalable()): ?>
<div class="box-tocart">
    <div class="fieldset">
    <?php  //echo"<pre/>"; print_r($_product->getReserveAndCollect());exit; ?>
        <?php if ($totalqty == 0  && $deliveryWeek == 'Sofort lieferbar'):?>
                <?php $buttonTitle = __('Ausverkauft'); ?>
                <div class="actions">
                    <button type="button"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary viewonly"
                            id="product-viewonly-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
         <?php elseif ($_product->getProductStatus() == 1):?>
                <?php $buttonTitle = __('Ansichtsprodukt'); ?>
                <div class="actions">
                    <button type="button"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary viewonly"
                            id="product-viewonly-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
        <?php else:?>
            <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                <div class="control">
                    <select class="input-text qty" name="qty" id="qty">
                        <?php 
                            $qty = 0;

                            if($totalqty < 20)
                            {
                                $qty = 12;
                            }
                            else
                            {
                                $qty = 20;
                            }
                        ?>
                        <option selected="selected" value="1">1</option>
                        <?php for ($i=2; $i <= $qty; $i++):?>
                            <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                        <?php endfor; ?>
                    </select>
                </div> 
            </div>
            <?php endif; ?>  

            <?php if(!$_product->getReserveAndCollect()): ?>
                    <?php $buttonTitle = __('Add to Cart'); ?>
                    <div class="actions">
                        <button type="submit"
                                title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                                class="action primary tocart"
                                id="product-addtocart-button">
                            <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                        </button>
                        <?php echo $block->getChildHtml('', true) ?>
                    </div>
            <?php else: ?>
                <?php $buttonTitle = __('Jetzt reservieren'); ?>
                <div class="actions">
                    <input type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary reserve-collect"
                            id="product-reserveandcollect-button"
                            value="<?php /* @escapeNotVerified */ echo $buttonTitle ?>">
                    </input>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>
<?php else:?>
<div class="box-tocart">
    <div class="fieldset">
        <?php $buttonTitle = __('Ausverkauft'); ?>
        <div class="actions">
            <button type="button"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary viewonly"
                    id="product-viewonly-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<?php endif; ?>

<?php if ($_product->getReserveAndCollect()): ?>
<script>
require([
    "jquery"
], function($){
    $(document).ready(function(){         
        var actionUrl = "<?php echo $block->getBaseUrl() . 'storelocator/'; ?>";
        $("#product_reserve_form").attr("action", actionUrl);
        $(document).on("click", "#product-reserveandcollect-button", function(){
            // $("#product_addtocart_form").submit();
            $( "#product_reserve_form" ).submit();
        });
        
    });
});
</script>
<?php endif; ?>

