<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_layoutHelper = $this->helper('ThinkIdeas\TipsOfExperts\Helper\Layout');
?>

<?php $listingBlockItems = $_layoutHelper->getListingBlockItems(); ?>

<?php //$listingBlockItems = []; ?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div>
    <?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
    <img class="no-result-found-img" src="<?php echo $this->getViewFileUrl('images/Weko_Empty_Cat.jpg'); ?>" />
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>

                <?php
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
                    $totalqty =  $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());
                    $attribute_code = 'delivery_time';
                    $deliveryWeek =  $_product->getResource()->getAttribute($attribute_code)->getFrontend()->getValue($_product);
                    $attribute_code = 'delivery_time_color';
                    $deliveryWeekColor =  $_product->getResource()->getAttribute($attribute_code)->getFrontend()->getValue($_product);
                    $week = filter_var($deliveryWeek, FILTER_SANITIZE_NUMBER_INT);                    
                ?>
                <?php while(array_key_exists($iterator, $listingBlockItems)): ?>
                    <li class="item product product-item custom-section position-<?php echo $iterator?>">
                    	<div class="tip-content-trigger">
                    		<?php echo $_layoutHelper->filterOutputHtml($listingBlockItems[$iterator], $block->getLayout()); ?>
                    	</div>
                    	
                        <div class="tip-content-popup <?php echo count($_productCollection) ?>" >
                            <?php echo $_layoutHelper->filterSubOutputHtml($listingBlockItems[$iterator], $block->getLayout()); ?>
                        </div>
                    <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                    <?php $iterator++; ?>
                <?php endwhile; ?>

                <?php if ($totalqty == 0  && $deliveryWeek == 'Sofort lieferbar' && $_product->getIsSalable()): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item out-of-stock-product">' : '</li><li class="item product product-item out-of-stock-product">' ?>

                <?php else:?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php endif; ?>

                <div class="product-item-info" data-container="product-grid">
                    <?php //if ($totalqty < 1 || $week == '6' || $week == '8'):?>
                    <?php if ($totalqty == 0  && $deliveryWeek == 'Sofort lieferbar' && $_product->getIsSalable()): ?>
                            <div class="stock-cover"><span>Leider ausverkauft</span></div>
                   
          
                    <?php endif;?>
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php if ($_product->getReserveAndCollect()):?>
                <?php endif; ?>
				<div class="shadow_block">	
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">

                        <?php echo $productImage->toHtml(); ?>
                        <div class="dis-tag"><?php echo $this->helper('ThinkIdeas\Additional\Helper\Data')->DisplayDiscountLabel($_product); ?></div>
                    </a>
				</div>

                    <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                            <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                        <?php endif; ?>
                    </div>

                    <div class="product details product-item-details">      
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                               <?php ;
                               if (strlen($_product->getName()) > 31)
                                {
                                    $namestr = array();
                                    $namestr[] = substr($_product->getName(), 0, 31);
                                    $namestr[] = substr($_product->getName(), 31, strlen($_product->getName())-30);
                                    $name = implode($namestr, "-");
                                }
                                else{
                                    $name = $_product->getName();
                                }

                                ?>
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $name, 'name'); ?>
                            </a>
                        </strong>
                        
                            <?php echo $block->getProductDetailsHtml($_product); ?>                            
                        
                        <div class="listing-product short-description-product product-item-short-description">
                        <?php if ($showDescription):?>                                
                            <?php /* @escapeNotVerified */ $desc =  $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ;

                                $desc = strlen($desc) > 30 ? substr($desc,0,30)."..." : $desc;
                                echo __($desc);
                            ?>                                    
                        <?php endif; ?>
                        </div>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <div class="product-status-color <?php echo strtolower($deliveryWeekColor); ?>">
                        <?php if ($_product->getIsSalable()): ?>
                            <?php if ($totalqty == 0  && $deliveryWeek == 'Sofort lieferbar'):?>
                                    <div class="product actions product-item-actions">
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Nicht auf Lager ') ?></span></div>
                                          <?php if($week){ ?>
                                            <div class="stock-count"><?php echo " - " .$week;?><span> <?php /* @escapeNotVerified */ echo __('&nbsp Wochen Lieferzeit') ?></span></div>

                                        <?php } ?>
                                    </div>
                            <?php elseif ($_product->getProductStatus() == 1):?>
                                    <div class="product actions product-item-actions">
                                        <div class="stock available view-only-status"><span><?php /* @escapeNotVerified */ echo __('ANSICHTSPRODUKT') ?></span></div>
                                    </div>
                            <?php elseif (!$_product->getReserveAndCollect()):?>
                                    <div class="product actions product-item-actions">
                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('Auf Lager ') ?></span></div>
                                        <?php if($_product->getDeliveryTimeInDays()): ?>
                                            <div class="stock-count <?php echo strtolower($deliveryWeekColor); ?>"><?php echo $_product->getDeliveryTimeInDays();?><span> <?php /* @escapeNotVerified */ echo __('&nbsp Tage Lieferzeit') ?></span></div>
                                        <?php endif;?>
                                        </div>
                            <?php else:?>
                                    <div class="product actions product-item-actions">
                                        <div class="stock available typerc-stock-status"><span><?php /* @escapeNotVerified */ echo __('Nur Abholung möglich ') ?></span></div>
                                    </div>
                            <?php endif;?>
                        <?php else:?>
                            <div class="product actions product-item-actions">
                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Nicht auf Lager ') ?></span></div>
                                  <?php if($week){ ?>
                                    <div class="stock-count"><?php echo " - " .$week;?><span> <?php /* @escapeNotVerified */ echo __('&nbsp Wochen Lieferzeit') ?></span></div>

                                <?php } ?>
                            </div>
                        <?php endif; ?>
                        </div>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                <?php if ($_product->getIsSalable()): ?>
                                            <?php if ($totalqty == 0  && $deliveryWeek == 'Sofort lieferbar'):?>
                                                <div class="main-btn1"><a class="action tocart primary out-of-stock" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php /* @escapeNotVerified */ echo __('Leider Aktuell Ausverkauft') ?></a></div>
                                            <?php elseif ($_product->getProductStatus() == 1):?>
                                                <div class="main-btn1"><a class="action tocart primary out-of-stock" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php /* @escapeNotVerified */ echo __('Ansichtsprodukt') ?></a></div>
                                            <?php elseif ($_product->getReserveAndCollect()):?>
                                                <div class="main-btn1"><a class="action tocart primary reserved-btn" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><span><?php /* @escapeNotVerified */ echo __('In einer Filiale reservieren') ?></span></a></div>
                                            <?php else:?>
                                                        <div class="main-btn1"><a class="action tocart primary" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><span><?php /* @escapeNotVerified */ echo __('Zum Produkt') ?></span></a></div>
                                            <?php endif;?>
                                    <?php else: ?>
                                        <div class="main-btn1"><a class="action tocart primary out-of-stock" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php /* @escapeNotVerified */ echo __('Leider Aktuell Ausverkauft') ?></a></div>
                                    <?php endif; ?>
                                </div>                        
                            </div>
                        </div>
                    </div>
                </div>
            <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script>
require([
    "jquery",
], function($){
    $(".toolbar-products .pages .pages-items li a").click(function(){
        $('html, body').scrollTop(0);
    });

    $(".tip-content-trigger").click(function(){
    	$('.tip-content-open .tip-content-popup').slideUp("slow");
    	if(!$(this).parent().hasClass('tip-content-open')) {
    		$('.product-item').removeClass('tip-content-open');
    		$(this).parent().addClass('tip-content-open');
			$(this).next().slideDown("slow");
    	}
    	else
    		$('.product-item').removeClass('tip-content-open');
    });

    $(".close-popup").click(function(){
        $(this).closest('.tip-content-popup').slideUp("slow");
        $(this).closest('.product-item').removeClass('tip-content-open');
    });
})
</script>

