<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart totals template
 * @var $block \Magento\Checkout\Block\Cart\Totals
 */
?>
<?php
$finalSubTotal = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($block->getQuote()->getSubtotal(),2),true,false);
$freeShipping = 100;
$moreFreeShipping = '';
if($block->getQuote()->getSubtotal() < $freeShipping){
    $moreFreeShipping = $freeShipping - $block->getQuote()->getSubtotal();
    $moreFreeShipping = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($moreFreeShipping,2),true,false);
}
?>
<div id="cart-totals" class="cart-totals" data-bind="scope:'block-totals'">
    <div class="title">
        <strong id="block-shipping-heading" role="heading" aria-level="2">
            <?php /* @escapeNotVerified */ //echo $block->getQuote()->isVirtual() ? __('Estimate Tax') : __('Estimate Shipping and Tax') ?>
            <?php echo __('Summary'); ?>
        </strong>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
            {
                "#cart-totals": {
                    "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                }
            }
    </script>
</div>
<?php if($moreFreeShipping): ?>
    <div id="free-shiippiing-text" style="display: none">Es fehlen noch <span><?php echo $moreFreeShipping ;?></span> für eine versandkostenfreie Lieferung!</div>
<?php endif; ?>

