<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage() && $this->getRequest()->getModuleName()=='cms'):?>
    <strong class="logo">
<?php else: ?>
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
<?php endif ?>
        <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
<?php if ($block->isHomePage()):?>
    </strong>
<?php else:?>
    </a>
<?php endif?>



<script type="text/javascript">
require(['jquery'], function($) {
    jQuery(document).ready(function() {

        /** Sticky topmenu*/
        jQuery(window).scroll(function(){
           if (jQuery(this).scrollTop() > 110) {
                jQuery('body').addClass('stickyyyy');
            } 
            else {
                $('body').removeClass('stickyyyy');
            }
            
            if ($(this).scrollTop() > 175) {
               $('body').addClass('slideDown');
            } 
            else {
               $('body').removeClass('slideDown');
            }

        });

        jQuery(".menu-body").hover(function(){
            jQuery('.menu-body').each(function(i, obj) {
                jQuery(this).css("display","none");
            }); 
        })

        jQuery(".navigation .level0.parent").hover(function(){
            console.log(jQuery(this).find(".menu-body").attr("class"));
            jQuery('.menu-body').each(function(i, obj) {
                jQuery(this).css("display","none");
            });
            jQuery(this).find(".menu-body").css("display","block");

        },function(e){ 
            jQuery(jQuery(this).children(".menu-body").css("display","none"));
        });
    });
});
</script>
